CREATE DATABASE catalog_of_my_things;

CREATE TABLE music_albums (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    artist VARCHAR(100) NOT NULL,
    genre VARCHAR(100) NOT NULL,
    publish_date DATE,
    on_spotify BOOLEAN,
    FOREIGN KEY (genre_id) REFERENCES genre (id),
    FOREIGN KEY (label_id) REFERENCES label (id),
    FOREIGN KEY (author_id) REFERENCES Author (id)
);

CREATE TABLE genre (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
);

CREATE TABLE Author(
  id SERIAL PRIMARY KEY,
  game_id INTEGER NOT NULL,
  label_id INTEGER NOT NULL,
  genre_id INTEGER NOT NULL,
  first_name VARCHAR NOT NULL,
  last_name VARCHAR NOT NULL,
)

CREATE TABLE Game (
	id SERIAL PRIMARY KEY,
	multiplayer VARCHAR NOT NULL,
	last_played_at DATE NOT NULL,
	publish_date DATE NOT NULL,
	first_name VARCHAR NOT NULL,
	last_name VARCHAR NOT NULL,
)

BEGIN;

ALTER TABLE Author
ADD (game_id) INT REFERENCES Game(id);
ADD (label_id) INT REFERENCES Label(id);
ADD (genre_id) INT REFERENCES Genre(id);
SELECT * FROM Item
ORDER BY id;

COMMIT;