CREATE DATABASE catalog_of_my_things;

CREATE TABLE music_albums (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    artist VARCHAR(100) NOT NULL,
    genre VARCHAR(100) NOT NULL,
    publish_date DATE,
    on_spotify BOOLEAN,
    FOREIGN KEY (genre_id) REFERENCES genre (id),
    FOREIGN KEY (label_id) REFERENCES label (id),
    FOREIGN KEY (author_id) REFERENCES author (id)
);

CREATE TABLE genre (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
);